# Generated by Django 5.2.17 on 2026-10-08 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_consentrecord'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='consentrecord',
            new_name='users_conse_user_id_9b8797_idx',
            old_name='users_cons_user_id_2e6b1a_idx',
        ),
    ]
